DFC.ServiceTaxonomy.Taxonomies/Models/TaxonomyPart.cs
using System.Collections.Generic;
using OrchardCore.ContentManagement;

namespace DFC.ServiceTaxonomy.Taxonomies.Models
{
    // This part is added automatically to all taxonomies
    public class TaxonomyPart : ContentPart
    {
        public string TermContentType { get; set; }
        public List<ContentItem> Terms { get; set; } = new List<ContentItem>();
    }
}

DFC.ServiceTaxonomy.Taxonomies/Models/TermPart.cs
using OrchardCore.ContentManagement;

namespace DFC.ServiceTaxonomy.Taxonomies.Models
{
    // This part is added automatically to all terms
    public class TermPart : ContentPart
    {
        public string TaxonomyContentItemId { get; set; }
    }
}

DFC.ServiceTaxonomy.Taxonomies/ViewModels/TaxonomyPartViewModel.cs
using DFC.ServiceTaxonomy.Taxonomies.Models;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using OrchardCore.ContentManagement;

namespace DFC.ServiceTaxonomy.Taxonomies.ViewModels
{
    public class TaxonomyPartViewModel
    {
        public string TaxonomyContentItemId => ContentItem.ContentItemId;

        [BindNever]
        public ContentItem ContentItem { get; set; }

        [BindNever]
        public TaxonomyPart TaxonomyPart { get; set; }
    }
}

DFC.ServiceTaxonomy.Taxonomies/ViewModels/TermPartViewModel.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using OrchardCore.ContentManagement;

namespace DFC.ServiceTaxonomy.Taxonomies.ViewModels
{
    public class TermPartViewModel
    {
        public string TermContentItemId => ContentItem.ContentItemId;
        public string TaxonomyContentItemId { get; set; }
        public IEnumerable<ContentItem> ContentItems { get; set; }
        public dynamic Pager { get; set; }

        [BindNever]
        public ContentItem ContentItem { get; set; }
    }
}

DFC.ServiceTaxonomy.Taxonomies/Controllers/TagController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DFC.ServiceTaxonomy.Taxonomies.Models;
using DFC.ServiceTaxonomy.Taxonomies.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using OrchardCore.Admin;
using OrchardCore.ContentManagement;
using OrchardCore.ContentManagement.Handlers;
using OrchardCore.ContentManagement.Metadata;
using OrchardCore.ContentManagement.Metadata.Settings;
using OrchardCore.DisplayManagement.ModelBinding;
using OrchardCore.Modules;
using YesSql;

namespace DFC.ServiceTaxonomy.Taxonomies.Controllers
{
    [Admin]
    public class TagController : Controller, IUpdateModel
    {
        private readonly IContentManager _contentManager;
        private readonly IAuthorizationService _authorizationService;
        private readonly IContentDefinitionManager _contentDefinitionManager;
        private readonly IEnumerable<IContentHandler> _contentHandlers;
        private readonly ISession _session;
        private readonly ILogger _logger;

        public TagController(
            IContentManager contentManager,
            IAuthorizationService authorizationService,
            IContentDefinitionManager contentDefinitionManager,
            IEnumerable<IContentHandler> contentHandlers,
            ISession session,
            ILogger<TagController> logger)
        {
            _contentManager = contentManager;
            _authorizationService = authorizationService;
            _contentDefinitionManager = contentDefinitionManager;
            _contentHandlers = contentHandlers;
            _session = session;
            _logger = logger;
        }

        [HttpPost]
        [ActionName("Create")]
        public async Task<IActionResult> CreatePost(string taxonomyContentItemId, string displayText)
        {
            if (!await _authorizationService.AuthorizeAsync(User, Permissions.ManageTaxonomies))
            {
                return Unauthorized();
            }

            ContentItem taxonomy;

            var contentTypeDefinition = _contentDefinitionManager.GetTypeDefinition("Taxonomy");

            if (!contentTypeDefinition.GetSettings<ContentTypeSettings>().Draftable)
            {
                taxonomy = await _contentManager.GetAsync(taxonomyContentItemId, VersionOptions.Latest);
            }
            else
            {
                taxonomy = await _contentManager.GetAsync(taxonomyContentItemId, VersionOptions.DraftRequired);
            }

            if (taxonomy == null)
            {
                return NotFound();
            }

            var part = taxonomy.As<TaxonomyPart>();

            // Create tag term but only run content handlers not content item display manager update editor.
            // This creates empty parts, if parts are attached to the tag term, with empty data.
            // But still generates valid autoroute paths from the handler. 
            var contentItem = await _contentManager.NewAsync(part.TermContentType);
            contentItem.DisplayText = displayText;
            contentItem.Weld<TermPart>();
            contentItem.Alter<TermPart>(t => t.TaxonomyContentItemId = taxonomyContentItemId);

            var updateContentContext = new UpdateContentContext(contentItem);

            await _contentHandlers.InvokeAsync((handler, updateContentContext) => handler.UpdatingAsync(updateContentContext), updateContentContext, _logger);
            await _contentHandlers.Reverse().InvokeAsync((handler, updateContentContext) => handler.UpdatedAsync(updateContentContext), updateContentContext, _logger);

            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            // Tag terms are always added to the root taxonomy element.
            taxonomy.Alter<TaxonomyPart>(part => part.Terms.Add(contentItem));

            // Auto publish draftable taxonomies when creating a new tag term.
            if (contentTypeDefinition.GetSettings<ContentTypeSettings>().Draftable)
            {
                await _contentManager.PublishAsync(taxonomy);
            }
            else
            {
                _session.Save(taxonomy);
            }

            var viewModel = new CreatedTagViewModel
            {
                ContentItemId = contentItem.ContentItemId,
                DisplayText = contentItem.DisplayText
            };

            return Ok(viewModel);
        }
    }
}

DFC.ServiceTaxonomy.Taxonomies/Views/Content.TermAdmin.cshtml
@using Newtonsoft.Json.Linq;

@inject OrchardCore.ContentManagement.Display.IContentItemDisplayManager ContentItemDisplayManager
@inject OrchardCore.DisplayManagement.ModelBinding.IUpdateModelAccessor ModelUpdaterAccessor

@{
    ContentItem contentItem = Model.ContentItem;
    JArray termsArray = contentItem.Content.Terms;
    var index = 0;
}

<li class="menu-item" id="menu-id-@Model.Index" data-index="@Model.Index">
    <div class="menu-item menu-item-title list-group-item">
        <div class="properties">
            <div class="related">
                <a asp-action="Edit"
                   asp-controller="Admin"
                   asp-route-area="DFC.ServiceTaxonomy.Taxonomies"
                   asp-route-taxonomyContentItemId="@Model.TaxonomyPart.ContentItem.ContentItemId"
                   asp-route-taxonomyItemId="@Model.ContentItem.ContentItemId"
                   class="btn btn-success btn-sm">
                    @T["Edit"]
                </a>
                <a class="btn btn-primary btn-sm"
                    asp-route-action="Create"
                    asp-route-controller="Admin"
                    asp-route-id="@Model.TaxonomyPart.TermContentType"
                    asp-route-taxonomyContentItemId="@Model.TaxonomyPart.ContentItem.ContentItemId"
                    asp-route-taxonomyItemId="@Model.ContentItem.ContentItemId"
                    asp-route-area="DFC.ServiceTaxonomy.Taxonomies">
                    @T["Add"]
                </a>
                <a asp-action="Delete"
                   asp-controller="Admin"
                   asp-route-area="DFC.ServiceTaxonomy.Taxonomies"
                   asp-route-taxonomyContentItemId="@Model.TaxonomyPart.ContentItem.ContentItemId"
                   asp-route-taxonomyItemId="@Model.ContentItem.ContentItemId"
                   data-url-af="RemoveUrl UnsafeUrl"
                   class="btn btn-danger btn-sm">
                    @T["Delete"]
                </a>
            </div>

            <span>@contentItem</span>

            @if (Model.Content != null)
            {
                @await DisplayAsync(Model.Content)
            }
        </div>
    </div>

    <ol class="menu-item menu-item-links">
        @if (termsArray != null)
        {
            var updater = ModelUpdaterAccessor.ModelUpdater;

            @foreach (JObject termObject in termsArray.OrderBy(term => (string)term["DisplayText"]))
            {
                var term = termObject.ToObject<ContentItem>();
                dynamic termShape = await ContentItemDisplayManager.BuildDisplayAsync(term, updater, "TermAdmin");
                termShape.TaxonomyPart = Model.TaxonomyPart;
                termShape.Index = Model.Index + "-" + index++;
                @await DisplayAsync(termShape)
            }
        }
    </ol>
</li>

DFC.ServiceTaxonomy.Taxonomies/Views/ContentPart.TermAdmin.cshtml
@using OrchardCore.Mvc.Utilities

@{
    string name = Model.Metadata.Name;
}

@if (Model.Content != null)
{
    // We don't render anything from custom parts in the terms list
    // This can be customized per part by creating custom templates

    @*<div class="contentpart contentpart-@name.HtmlClassify()">
        @await DisplayAsync(Model.Content)
    </div>*@    
}

DFC.ServiceTaxonomy.Taxonomies/Views/NavigationItemText-taxonomyfilters.Id.cshtml
<span class="icon"><i class="fa fa-tags" aria-hidden="true"></i></span><span class="title">@T["Taxonomy Filters"]</span>

DFC.ServiceTaxonomy.Taxonomies/Views/TaxonomyContentsAdminListSettings.Edit.cshtml
@model TaxonomyContentsAdminListSettingsViewModel

<div class="form-group" asp-validation-class-for="TaxonomyEntries">
    <label asp-for="TaxonomyEntries">@T["Taxonomies"]</label>
    <span class="hint dashed">@T["The taxonomies to filters in the contents list."]</span>

    <div class="row">
        @for (int i = 0; i < Model.TaxonomyEntries.Length; i++)
        {
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-2">
                <input type="hidden" name="@Html.NameFor(m => m.TaxonomyEntries[i].ContentItemId)"
                       value="@Model.TaxonomyEntries[i].ContentItemId" />
                <div class="form-group custom-control custom-checkbox">
                    <input asp-for="TaxonomyEntries[i].IsChecked" class="custom-control-input content-type-checkbox" />
                    <label asp-for="TaxonomyEntries[i].IsChecked" class="custom-control-label">@Model.TaxonomyEntries[i].DisplayText</label>
                </div>
            </div>
        }
    </div>

</div>

DFC.ServiceTaxonomy.Taxonomies/Views/TaxonomyField-Tags.Display.cshtml
@model DFC.ServiceTaxonomy.Taxonomies.ViewModels.DisplayTaxonomyFieldTagsViewModel
@using OrchardCore.Mvc.Utilities;

@{
    var name = (Model.PartFieldDefinition.PartDefinition.Name + "-" + Model.PartFieldDefinition.Name).HtmlClassify();
}

<div class="field field-type-taxonomyfield field-display-mode-tags field-name-@name">
    @foreach (var tagName in Model.TagNames)
    {
        <span class="taxonomy-tag-term">@tagName</span>
    }
</div>

DFC.ServiceTaxonomy.Taxonomies/Views/TaxonomyField-Tags.DisplayOption.cshtml
@{
    string currentDisplayMode = Model.DisplayMode;
}
<option value="Tags" selected="@(currentDisplayMode == "Tags")">@T["Tags"]</option>

DFC.ServiceTaxonomy.Taxonomies/Views/TaxonomyField-Tags.Edit.cshtml
@model DFC.ServiceTaxonomy.Taxonomies.ViewModels.EditTaxonomyFieldViewModel
@using DFC.ServiceTaxonomy.Taxonomies.Settings;
@using OrchardCore.ContentManagement.Metadata.Models
@using Newtonsoft.Json.Linq;
@using Microsoft.AspNetCore.Authorization;
@inject IAuthorizationService AuthorizationService;

@{
    var taxonomySettings = Model.PartFieldDefinition.GetSettings<TaxonomyFieldSettings>();
    var tagsSettings = Model.PartFieldDefinition.GetSettings<TaxonomyFieldTagsEditorSettings>();
    // Create a flat object for vue multi select with required properties.
    var allTagTerms = JArray.FromObject(Model.TermEntries.Select(te => new { contentItemId = te.ContentItemId, selected = te.Selected, displayText = te.Term.DisplayText, isLeaf = te.IsLeaf }));

    var partName = Model.PartFieldDefinition.PartDefinition.Name;
    var fieldName = Model.PartFieldDefinition.Name;

    var createTagUrl = Url.Action("Create", "Tag", new { area = "DFC.ServiceTaxonomy.Taxonomies" });

    bool open = tagsSettings.Open;
    if (!await AuthorizationService.AuthorizeAsync(User, DFC.ServiceTaxonomy.Taxonomies.Permissions.ManageTaxonomies))
    {
        open = false;
    }

    var vueElementId = $"TaxonomyField-Tags_{partName}_{fieldName}_{Guid.NewGuid().ToString("n")}";
    var termEntriesKey = Html.NameFor(x => x.TermEntries);

}

<script asp-src="~/DFC.ServiceTaxonomy.Taxonomies/Scripts/tags-editor.min.js" debug-src="~/DFC.ServiceTaxonomy.Taxonomies/Scripts/tags-editor.js" asp-name="tags-editor" at="Foot" depends-on="vuejs, vue-multiselect"></script>
<style asp-src="~/DFC.ServiceTaxonomy.Taxonomies/Styles/tags-editor.min.css" debug-src="~/DFC.ServiceTaxonomy.Taxonomies/Styles/tags-editor.css" asp-name="tags-editor" depends-on="vue-multiselect"></style>

<label>@Model.PartFieldDefinition.DisplayName()</label>

@* Antiforgery token required for the ajax post to create a new tag *@
@Html.AntiForgeryToken()

@if (!String.IsNullOrEmpty(taxonomySettings.Hint))
{
    <span class="hint dashed">@taxonomySettings.Hint</span>
}

@if (Model.Taxonomy == null)
{
    <div class="alert alert-danger" role="alert">
        @T["The taxonomy could not be found. Please check the settings for this field."]
    </div>
}
else
{
    <div class="form-group">
        <div id="@vueElementId" class="tags" data-taxonomy-content-item-id="@Model.Taxonomy.ContentItemId" data-open="@open.ToString().ToLower()" data-leaves-only="@taxonomySettings.LeavesOnly.ToString().ToLower()" data-create-tag-error-message="@T["Error creating tag"]" data-all-tag-terms="@allTagTerms" data-create-tag-url="@createTagUrl" data-term-entries-key="@termEntriesKey" data-content-item-id-key="@nameof(TermEntry.ContentItemId)" data-selected-key="@nameof(TermEntry.Selected)">

            <div class="form-group">
                <div class="w-xl-50">
                    <input v-for="tagTerm in allTagTerms" v-bind:name="termEntriesContentItemName(tagTerm)" v-bind:value="tagTerm.contentItemId" type="hidden" />
                    <input v-for="tagTerm in allTagTerms" v-bind:name="termEntriesSelectedName(tagTerm)" v-bind:value="tagTerm.selected" type="hidden" />

                    <vue-multiselect v-model="selectedTagTerms"
                                     placeholder="@T["Type to search"]"
                                     select-label="@T["Select"]"
                                     deselect-label="@T["Remove"]"
                                     :options="selectableTagTerms"
                                     :multiple="@((!taxonomySettings.Unique).ToString().ToLower())"
                                     :show-labels="false"
                                     :close-on-select="@taxonomySettings.Unique.ToString().ToLower()"
                                     :disabled="isDisabled"
                                     track-by="contentItemId"
                                     label="displayText"
                                     @@select="onSelect"
                                     @@remove="onRemove"
                                     :taggable="@open.ToString().ToLower()"
                                     tag-position="bottom"
                                     tag-placeholder="@T["Press enter to create a tag"]"
                                     @@tag="createTagTerm">
                        <template slot="noResult">
                            @T["No tags found"]
                        </template>
                        <template slot="noOptions">
                            @T["No tags found"]
                        </template>
                    </vue-multiselect>
                </div>
            </div>

        </div>
    </div>

    <script depends-on="tags-editor" at="Foot">
        initializeTagsEditor(document.querySelector("#@vueElementId"));
    </script>
}

DFC.ServiceTaxonomy.Taxonomies/Views/TaxonomyField.DisplayOption.cshtml
@{
    string currentDisplayMode = Model.DisplayMode;
}
<option value="" selected="@String.IsNullOrEmpty(currentDisplayMode)">@T["Standard"]</option>

DFC.ServiceTaxonomy.Taxonomies/Views/TaxonomyField.Option.cshtml
@{
    string currentEditor = Model.Editor;
}
<option value="" selected="@String.IsNullOrEmpty(currentEditor)">@T["Standard"]</option>

DFC.ServiceTaxonomy.Taxonomies/Views/TaxonomyField.cshtml
@model DFC.ServiceTaxonomy.Taxonomies.ViewModels.DisplayTaxonomyFieldViewModel
@using OrchardCore.Mvc.Utilities;

@{
    var name = (Model.PartFieldDefinition.PartDefinition.Name + "-" + Model.PartFieldDefinition.Name).HtmlClassify();
}

<div class="field field-type-taxonomyfield field-name-@name">
    @foreach (var contentItemId in Model.TermContentItemIds)
    {
        var term = await Orchard.GetTaxonomyTermAsync(Model.TaxonomyContentItemId, contentItemId);
        <span class="taxonomy-term">@term</span>
    }
</div>

DFC.ServiceTaxonomy.Taxonomies/Views/TaxonomyFieldSettings.Edit.cshtml
@using OrchardCore.ContentManagement
@using OrchardCore.ContentManagement.Records
@using YesSql;

@model DFC.ServiceTaxonomy.Taxonomies.Settings.TaxonomyFieldSettings

@inject ISession Session

@{
    var taxonomies = await Session.Query<ContentItem, ContentItemIndex>().Where(x => x.ContentType == "Taxonomy" && x.Latest).ListAsync();
}

<div class="form-group">
    <div class="w-md-75 w-xl-50 pr-md-3">
        <label asp-for="Hint">@T["Hint"]</label>
        <textarea asp-for="Hint" rows="2" class="form-control"></textarea>
    </div>
    <span class="hint">@T["The hint text to display for this field on the editor."]</span>
</div>

<div class="form-group">
    <div class="w-md-50 pr-md-3">
        <label asp-for="TaxonomyContentItemId">@T["Taxonomy"]</label>
        <select asp-for="TaxonomyContentItemId" class="form-control">
            @foreach (var taxonomy in taxonomies)
            {
                <option value="@taxonomy.ContentItemId">@taxonomy</option>
            }
        </select>
    </div>
</div>

<div class="form-group">
    <div class="custom-control custom-checkbox">
        <input asp-for="Required" type="checkbox" class="custom-control-input" />
        <label class="custom-control-label" asp-for="Required">@T["Required"]</label>
        <span class="hint dashed">@T["Whether at least one element is selected."]</span>
    </div>
</div>

<div class="form-group">
    <div class="custom-control custom-checkbox">
        <input asp-for="Unique" type="checkbox" class="custom-control-input" />
        <label class="custom-control-label" asp-for="Unique">@T["Unique"]</label>
        <span class="hint dashed">@T["Whether only one element can be selected."]</span>
    </div>
</div>

<div class="form-group">
    <div class="custom-control custom-checkbox">
        <input asp-for="LeavesOnly" type="checkbox" class="custom-control-input" />
        <label class="custom-control-label" asp-for="LeavesOnly">@T["Leaves only"]</label>
        <span class="hint dashed">@T["Whether leaves are the only items that can be selected."]</span>
    </div>
</div>

DFC.ServiceTaxonomy.Taxonomies/Views/TaxonomyFieldTagsEditorSettings.Edit.cshtml
@model DFC.ServiceTaxonomy.Taxonomies.Settings.TaxonomyFieldTagsEditorSettings

<div class="form-group field-editor field-editor-tags">
    <div class="custom-control custom-checkbox">
        <input asp-for="Open" type="checkbox" class="custom-control-input" />
        <label class="custom-control-label" asp-for="Open">@T["Open"]</label>
        <span class="hint dashed">@T["Whether new tags can be created inline. Note: When creating tags inline only the display text term property will be set."]</span>
    </div>
</div>

DFC.ServiceTaxonomy.Taxonomies/Views/TaxonomyPart.cshtml
@model TaxonomyPartViewModel
@using OrchardCore.Mvc.Utilities;
@{
    var name = ( "taxonomy-" + Model.TaxonomyPart.TermContentType).HtmlClassify();
}
<section class="taxonomy @name">
    <shape type="term" TaxonomyContentItemId="@Model.TaxonomyContentItemId" />
</section>

DFC.ServiceTaxonomy.Taxonomies/Views/TermItem.cshtml
@model dynamic
@{
    // Morphing the shape to keep Model untouched
    Model.Metadata.Alternates.Clear();
    Model.Metadata.Type = "TermContentItem";
}
<li>
    @await DisplayAsync(Model)
    @if ((bool)Model.HasItems)
    {
        <ul>
            @foreach (var item in Model.Items)
            {
                @await DisplayAsync(item)
            }
        </ul>
    }
</li>